""" General game constants """

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
FPS_LIMIT = 0  # 0 means Unlimited
GAMEDIR_NAME = 'grunzi'
MONOTYPE_FONT = 'monotype.ttf'
DEBUG_OUTPUT_FONT_SIZE = 12
VSYNC = False
MAIN_CHARACTER_ID = 'grunzi'

LEVEL_1_SIZE = (150, 150)
