""" General game constants """

GAMEDIR_NAME_WINDOWS = 'Grunzi'
GAMEDIR_NAME_LINUX = '.grunzi'
MONOTYPE_FONT = 'monotype.ttf'
REGULAR_FONT = 'laila.ttf'
DEBUG_OUTPUT_FONT_SIZE = 14
TEXT_FONT_SIZE = 16
MEDIUM_FONT_SIZE = 20
LARGE_FONT_SIZE = 24
DEBUG_TILE_FONT_SIZE = 12
MAIN_CHARACTER_ID = 'grunzi'
