""" General game constants """

GAMEDIR_NAME_WINDOWS = 'Grunzi'
GAMEDIR_NAME_LINUX = '.grunzi'
MONOTYPE_FONT = 'monotype.ttf'
DEBUG_OUTPUT_FONT_SIZE = 12
DEBUG_TILE_FONT_SIZE = 10
MAIN_CHARACTER_ID = 'grunzi'

LEVEL_1_SIZE = (150, 150)
