"""Keyboard controls"""

# XBOX 360 Controller Mapping
KEY_START = 7
KEY_A = 0
KEY_B = 1
KEY_X = 2
KEY_Y = 3

AXIS_X = 'x'
AXIS_Y = 'y'
KEY_LT = 'z'

KEY_LB = 4
KEY_RB = 5

PREVIOUS_ITEM = [KEY_LB]
NEXT_ITEM = [KEY_RB]

KEY_PAUSE = [KEY_START]
KEY_DISCARD = [KEY_START, KEY_X]
KEY_SPRINT = [KEY_LT]
KEY_SHOOT = [KEY_A]
KEY_GRUNT = [KEY_B]
KEY_USE = [KEY_X]
KEY_DROP = [KEY_Y]

KEY_MOVE_LEFT = []
KEY_MOVE_RIGHT = []
KEY_MOVE_UP = []
KEY_MOVE_DOWN = []

KEY_SELECT_INVENTORY = []

KEY_SCREENSHOT = []
KEY_TOGGLE_FPS = []
