""" Controller stuff """

# XBOX 360 Controller Mapping
KEY_START = 'start'
KEY_A = 'a'
KEY_B = 'b'
KEY_X = 'x'
KEY_Y = 'y'

LEFTSHOULDER = 'leftshoulder'
RIGHTSHOULDER = 'rightshoulder'

LEFTSTICK = 'leftstick'
RIGHTSTICK = 'rightstick'

AXIS_LEFT = -1.0
AXIS_RIGHT = 1.0
AXIS_UP = 1.0
AXIS_DOWN = -1.0

LEFT_TRIGGER = 'lefttrigger'
RIGHT_TRIGGER = 'righttrigger'

TRIGGER_ON = 1.0
TRIGGER_OFF = -1.0

KEY_PAUSE = [KEY_START]
KEY_DISCARD = [KEY_START, KEY_A]
KEY_SHOOT = [KEY_X]
KEY_GRUNT = [KEY_B]
KEY_USE = [KEY_A]
KEY_DROP = [KEY_Y]
PREVIOUS_ITEM = [LEFTSHOULDER]
NEXT_ITEM = [RIGHTSHOULDER]
KEY_SPRINT = [LEFTSTICK]

KEY_MENU_ITEM = [KEY_A]
KEY_MENU_BACK = [KEY_B]